"""empty message

Revision ID: edb14a7c58ce
Revises: a9369e3fbd18
Create Date: 2023-02-22 15:11:27.917131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb14a7c58ce'
down_revision = 'a9369e3fbd18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('characters', sa.String(length=500), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('director', sa.String(length=150), nullable=False),
    sa.Column('edited', sa.DateTime(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('opening_crawl', sa.String(length=500), nullable=False),
    sa.Column('planets', sa.String(length=550), nullable=False),
    sa.Column('producer', sa.String(length=150), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('species', sa.String(length=500), nullable=False),
    sa.Column('starships', sa.String(length=550), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('vehicles', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('MGLT', sa.String(length=150), nullable=False),
    sa.Column('cargo_capacity', sa.Integer(), nullable=False),
    sa.Column('consumables', sa.String(length=150), nullable=False),
    sa.Column('cost_in_credits', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('crew', sa.Integer(), nullable=False),
    sa.Column('edited', sa.Integer(), nullable=False),
    sa.Column('hyperdrive_rating', sa.Float(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=150), nullable=False),
    sa.Column('max_atmosphering_speed', sa.String(length=150), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('films', sa.String(length=900), nullable=False),
    sa.Column('pilots', sa.String(length=150), nullable=False),
    sa.Column('starship_class', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eye_colors', sa.String(length=120), nullable=False),
    sa.Column('films', sa.String(length=900), nullable=False),
    sa.Column('gender', sa.String(length=120), nullable=False),
    sa.Column('hair_colors', sa.String(length=120), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('homeworld', sa.String(length=120), nullable=False),
    sa.Column('mass', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('skin_color', sa.String(length=150), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('edited', sa.DateTime(), nullable=False),
    sa.Column('species', sa.String(length=500), nullable=False),
    sa.Column('starships', sa.String(length=900), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('vehicles', sa.String(length=200), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('gravity', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.Column('films', sa.String(length=800), nullable=True),
    sa.Column('orbital_period', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('residents', sa.String(length=500), nullable=True),
    sa.Column('rotation_period', sa.Integer(), nullable=True),
    sa.Column('surface_water', sa.Integer(), nullable=True),
    sa.Column('terrain', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=900), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('average_lifespan', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=120), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=False),
    sa.Column('edited', sa.DateTime(), nullable=False),
    sa.Column('eye_colors', sa.String(length=120), nullable=False),
    sa.Column('hair_colors', sa.String(length=120), nullable=False),
    sa.Column('homeworld', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('people', sa.String(length=900), nullable=False),
    sa.Column('films', sa.String(length=900), nullable=False),
    sa.Column('skin_colors', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_capacity', sa.Integer(), nullable=False),
    sa.Column('consumables', sa.String(length=150), nullable=False),
    sa.Column('cost_in_credits', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('crew', sa.Integer(), nullable=False),
    sa.Column('edited', sa.DateTime(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('manufacturer', sa.String(length=150), nullable=False),
    sa.Column('max_atmosphering_speed', sa.String(length=150), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('pilots', sa.String(length=500), nullable=False),
    sa.Column('films', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('vehicle_class', sa.String(length=150), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('starships_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('vehicles_id', sa.Integer(), nullable=True),
    sa.Column('characters_id', sa.Integer(), nullable=True),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['starships_id'], ['starships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicles_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')

    op.drop_table('user_favorite')
    op.drop_table('characters')
    op.drop_table('vehicles')
    op.drop_table('species')
    op.drop_table('planet')
    op.drop_table('people')
    op.drop_table('starships')
    op.drop_table('films')
    # ### end Alembic commands ###
